#!/usr/bin/env python
from optparse import OptionParser
import logging
import sys

from credentialhelper import Client, ConnectionRefusedException, Config, start_agent

def ask_password():
    import getpass
    print >>sys.stderr, "Password: ",
    return getpass.getpass('')

def ask_username():
    print >>sys.stderr, "Username: ",
    return raw_input()

def main():
    """Main entry point for the script."""
    
    usage = 'credentialcache [options] service_url'
    
    parser = OptionParser(usage=usage)
    parser.add_option("-u", "--username",
                      dest="retrieve_username",
                      help="print username",
                      action="store_true")
    parser.add_option("-s", "--password",
                      dest="retrieve_password",
                      help="print password",
                      action='store_true'
    )   
    parser.add_option("-c", "--config-dir",
                      dest="config_dir",
                      metavar="DIRECTORY",
                      help="configuration directory")
    (options, args) = parser.parse_args()

    if len(args) != 1:
        parser.print_help()
        return 1
    service = args[0]

    config = Config(options.config_dir)

    retrieve_password = options.retrieve_password
    retrieve_username = options.retrieve_username
    
    client = Client(config)
    try:
        client.connect()
    except ConnectionRefusedException:
        logging.debug("Starting agent");
        start_agent(config.get_socket_path())
        client.connect()


    do_update = False
        
    res = client.get(service)
    client.close()
    
    username = res.get('username')
    if username is None:
        username = ask_username()
        do_update = True     
    password = res.get('password')
    if password is None:
        password = ask_password()
        do_update = True

    if retrieve_username:
        print username
    if retrieve_password:
        print password

    if do_update:
        client = Client(config)
        client.connect()
        client.set(service, username, password)
        client.close()
                
    
if __name__ == '__main__':
    sys.exit(main())



