#!/usr/bin/env python

import os
import sys
import logging

from credentialhelper.agent import execute_from_command_line
                
if __name__ == '__main__':
    if os.getenv('CREDENTIALHELPER_DEBUG'):
        logging.basicConfig(level=logging.DEBUG)        
    execute_from_command_line(sys.argv)
