#!/usr/bin/env python
from optparse import OptionParser
import logging
import sys

from credentialhelper import Client, Config, fetch_credentials

def main():
    """Main entry point for the script."""
    
    usage = 'credentialcache [options] service_url'
    
    parser = OptionParser(usage=usage)
    parser.add_option("-u", "--username",
                      dest="retrieve_username",
                      help="print username",
                      action="store_true")
    parser.add_option("-s", "--password",
                      dest="retrieve_password",
                      help="print password",
                      action='store_true'
    )   
    parser.add_option("-c", "--config-dir",
                      dest="config_dir",
                      metavar="DIRECTORY",
                      help="configuration directory")
    (options, args) = parser.parse_args()

    if len(args) != 1:
        parser.print_help()
        return 1
    service = args[0]

    config = Config(options.config_dir)
    retrieve_password = options.retrieve_password
    retrieve_username = options.retrieve_username
    
    ( username, password, stored ) = fetch_credentials(service, config)

    if retrieve_username:
        print username
    if retrieve_password:
        print password

    if not stored:
        client = Client(config)
        client.connect()
        client.set(service, username, password)
        client.close()

    return 0
    
if __name__ == '__main__':
    if os.getenv('CREDENTIALHELPER_DEBUG'):
        logging.basicConfig(level=logging.DEBUG)        
    sys.exit(main())



